name = "SeparableMatchingEstim"
uuid = "6a2be2aa-f6b4-4069-b516-fad14aa2652d"
authors = ["Pauline Corblet <pzc208@nyu.edu>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CovarianceMatrices = "60f91f6f-d783-54cb-84f9-544141854719"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NonLinearProg = "59a653e0-4fd1-4c37-892e-cada1571c056"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"

[compat]
CovarianceMatrices = "0.30.3"
NonLinearProg = "0.1.0"
